# Basic
title: Lucy之家
subtitle: 程序要追求完美!
description: Hi,I’m Lucy,一枚小小的程序员,现就职于拓深科技有限公司,喜欢运动,喜欢瞎搞,Welcome to visit my home online,best wishes for you,thank you.
creator: <a href=“https://github.com/lucyios”>@lucyios</a>
url: "http://liluxin.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Lucy
    # duoshuo: 
    
# Social
social:
    github: lucyios
    gplus: 107108267983477358170
    mail: liluxinios@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
